const {test,before,after}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const {PGlite}=require('@electric-sql/pglite');
let db;const user='11111111-1111-4111-8111-111111111111',other='22222222-2222-4222-8222-222222222222';
before(async()=>{db=new PGlite();await db.exec("create role anon; create role authenticated; create role service_role bypassrls; create schema auth; create table auth.users(id uuid primary key);");await db.exec(fs.readFileSync('supabase/setup.sql','utf8'));await db.exec(fs.readFileSync('supabase/setup.sql','utf8'));await db.query('insert into auth.users values ($1),($2)',[user,other]);await db.query("insert into public.greekee_staff(user_id,display_name,locations) values($1,'Fiona',array['Punggol']),($2,'Caleb',array['Hougang'])",[user,other]);});
after(async()=>{await db.close();});
async function create(){const r=await db.query(`insert into greekee_orders(request_key,request_hash,customer_name,phone,location,fulfillment,order_date,fulfillment_date,source,items,subtotal_cents,total_cents) values(gen_random_uuid(),'hash','Test','91234567','Punggol','pickup','2026-09-24','2026-09-24','Website','[{"id":"item"}]',890,890) returning *`);return r.rows[0];}
test('schema reruns cleanly; every exposed table has RLS and no browser grants',async()=>{const r=await db.query("select relname,relrowsecurity from pg_class where relname in ('greekee_orders','greekee_staff','greekee_order_events','greekee_rate_limits')");assert.equal(r.rows.length,4);assert(r.rows.every(x=>x.relrowsecurity));for(const role of ['anon','authenticated']){await db.exec('set role '+role);await assert.rejects(db.query('select * from public.greekee_orders'),/permission denied/);await assert.rejects(db.query('select * from public.greekee_staff'),/permission denied/);await assert.rejects(db.query("select public.greekee_rate_limit('bad',1,10)"),/permission denied/);await db.exec('reset role');}});
test('price total database constraint rejects mismatches',async()=>{const o=await create();await assert.rejects(db.query('update greekee_orders set total_cents=1 where id=$1',[o.id]),/check constraint/);});
test('payment update and audit happen together with actor and timestamp',async()=>{const o=await create();await db.exec('set role service_role');const r=await db.query('select * from greekee_update_order($1,1,$2,$3)',[o.id,user,JSON.stringify({payment_status:'paid',order_status:'preparing'})]);await db.exec('reset role');assert.equal(r.rows[0].payment_status,'paid');assert.equal(r.rows[0].payment_checked_by,user);assert(r.rows[0].payment_checked_at);assert.equal(r.rows[0].revision,2);const events=await db.query('select * from greekee_order_events where order_id=$1',[o.id]);assert.equal(events.rows.length,1);assert.equal(events.rows[0].changes.payment_status.before,'unpaid');assert.equal(events.rows[0].changes.payment_status.after,'paid');});
test('stale edits fail and cannot overwrite another partner change',async()=>{const o=await create();await db.query('select * from greekee_update_order($1,1,$2,$3)',[o.id,user,'{"notes":"first"}']);await assert.rejects(db.query('select * from greekee_update_order($1,1,$2,$3)',[o.id,user,'{"notes":"stale"}']),/revision_conflict/);const r=await db.query('select notes from greekee_orders where id=$1',[o.id]);assert.equal(r.rows[0].notes,'first');});
test('wrong location, inactive staff and unearned refunds are denied',async()=>{const o=await create();await assert.rejects(db.query('select * from greekee_update_order($1,1,$2,$3)',[o.id,other,'{"notes":"x"}']),/not_authorized/);await assert.rejects(db.query('select * from greekee_update_order($1,1,$2,$3)',[o.id,user,'{"payment_status":"refunded"}']),/refund_requires_paid/);await db.query('update greekee_staff set active=false where user_id=$1',[user]);await assert.rejects(db.query('select * from greekee_update_order($1,1,$2,$3)',[o.id,user,'{"notes":"x"}']),/not_authorized/);await db.query('update greekee_staff set active=true where user_id=$1',[user]);});
test('rate limit persists across invocations; unsynced view clears only at current revision',async()=>{await db.exec('set role service_role');for(let i=0;i<2;i++)assert.equal((await db.query("select greekee_rate_limit('ip-hash',2,900) ok")).rows[0].ok,true);assert.equal((await db.query("select greekee_rate_limit('ip-hash',2,900) ok")).rows[0].ok,false);await db.exec('reset role');const o=await create();assert((await db.query('select * from greekee_unsynced_orders where id=$1',[o.id])).rows.length);await db.query('update greekee_orders set synced_revision=revision where id=$1',[o.id]);assert.equal((await db.query('select * from greekee_unsynced_orders where id=$1',[o.id])).rows.length,0);});
