const {test}=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');const crypto=require('node:crypto');
const secret='test-only-shared-secret-01234567890123456789';
function sheet(name){const cells=new Map(),charts=[];let maxRows=100,maxCols=26,fail=false;const key=(r,c)=>r+','+c;
 const col=s=>[...s].reduce((n,x)=>n*26+x.charCodeAt(0)-64,0);
 return {name,cells,charts,getName:()=>name,getMaxRows:()=>maxRows,getMaxColumns:()=>maxCols,insertRowsAfter(_,n){maxRows+=n;},insertColumnsAfter(_,n){maxCols+=n;},getLastRow(){return Math.max(0,...[...cells.keys()].map(k=>Number(k.split(',')[0])));},setFrozenRows(){},setFrozenColumns(){},setHiddenGridlines(){},setTabColor(){},setColumnWidths(){},setColumnWidth(){},setRowHeight(){},setRowHeights(){},hideColumns(){},getFilter:()=>null,getConditionalFormatRules:()=>[],setConditionalFormatRules(){},newChart(){const b={};for(const method of ['setChartType','addRange','setPosition','setNumHeaders','setHiddenDimensionStrategy','setOption'])b[method]=()=>b;b.build=()=>({});return b;},insertChart(c){charts.push(c);},getRange(r,c,n=1,m=1){if(typeof r==='string'){const [a,b=a]=r.split(':');const match=x=>/^([A-Z]+)(\d+)$/.exec(x);const x=match(a),y=match(b);r=Number(x[2]);c=col(x[1]);n=Number(y[2])-r+1;m=col(y[1])-c+1;}const band={setHeaderRowColor:()=>band,setFirstRowColor:()=>band,setSecondRowColor:()=>band};return {getValues:()=>Array.from({length:n},(_,i)=>Array.from({length:m},(_,j)=>cells.get(key(r+i,c+j))??'')),getDisplayValues(){return this.getValues().map(row=>row.map(String));},setValues(v){if(fail&&c===2){fail=false;throw Error('Simulated write failure');}v.forEach((row,i)=>row.forEach((x,j)=>cells.set(key(r+i,c+j),x)));return this;},setValue(v){cells.set(key(r,c),v);return this;},setFormula(v){cells.set(key(r,c),v);return this;},getCell(i,j){return this.getRange?this.getRange(r+i-1,c+j-1):{setValue:v=>cells.set(key(r+i-1,c+j-1),v),setFormula:v=>cells.set(key(r+i-1,c+j-1),v)};},getBandings:()=>[],applyRowBanding:()=>band,createFilter(){return this;},setNumberFormat(){return this;},setHorizontalAlignment(){return this;},setWrap(){return this;},merge(){return this;},setBackground(){return this;},setFontColor(){return this;},setFontFamily(){return this;},setFontSize(){return this;},setFontWeight(){return this;},setVerticalAlignment(){return this;}};},failNextData(){fail=true;}};}
function harness(){const original=sheet("🌟FIO's ORDERS Q3'26"),tabs=[original];original.getRange(21,1).setValue('Existing order headers');original.getRange(22,1).setValue('Existing customer');
 const ss={getSheetByName:name=>tabs.find(t=>t.name===name),insertSheet:name=>{const t=sheet(name);tabs.push(t);return t;}};let locked=false;
 const ctx=vm.createContext({console:{error(){},log(){}},Charts:{ChartType:{BAR:'BAR',COLUMN:'COLUMN',PIE:'PIE'},ChartHiddenDimensionStrategy:{SHOW_BOTH:'SHOW_BOTH'}},PropertiesService:{getScriptProperties:()=>({getProperty:()=>secret})},SpreadsheetApp:{BandingTheme:{LIGHT_GREY:'LIGHT_GREY'},newConditionalFormatRule(){const b={};for(const m of ['whenTextEqualTo','setBackground','setFontColor','setRanges'])b[m]=()=>b;b.build=()=>({});return b;},openById:()=>ss,flush(){}},LockService:{getScriptLock:()=>({waitLock(){locked=true;},hasLock:()=>locked,releaseLock(){locked=false;}})},Utilities:{Charset:{UTF_8:'utf8'},computeHmacSha256Signature:(payload,key)=>[...crypto.createHmac('sha256',key).update(payload).digest()],formatDate:()=>''},ContentService:{MimeType:{JSON:'json'},createTextOutput:s=>({setMimeType:()=>s})}});vm.runInContext(fs.readFileSync('google-sheets/Code.gs','utf8'),ctx);ctx.setupGreekeeSync();
 return {tabs,original,orders:ss.getSheetByName('Greekee Orders — TEST'),dashboard:ss.getSheetByName('Greekee Dashboard — TEST'),post(o,{badSignature=false,timestamp=Date.now(),environment='TEST'}={}){const payload=JSON.stringify({environment,timestamp,order:o});const signature=badSignature?'invalid':crypto.createHmac('sha256',secret).update(payload).digest('hex');return JSON.parse(ctx.doPost({postData:{contents:JSON.stringify({payload,signature})}}));}};}
function order(){return {id:'test-order',order_number:'GK-TEST',location:'Punggol',order_date:'2026-09-26',fulfillment_date:'2026-09-28',customer_name:'=IMPORTXML("bad")',phone:'+6591234567',revision:1,order_status:'pending',payment_status:'unpaid',source:'Website',notes:'Extra cold',point_of_contact:'Fiona',subtotal_cents:2380,discount_cents:101,total_cents:2679,delivery_fee_cents:400,items:[{id:'a',name:'Berry Bliss',sheet_name:'Berry Bliss',quantity:2,addons:[{name:'Mango',quantity:1,unit_cents:100}],line_cents:1980},{id:'b',name:'Plain',sheet_name:'Plain',quantity:1,addons:[],line_cents:400}]};}
test('TEST setup creates only dedicated order and visual dashboard tabs, preserving historical tabs',()=>{const h=harness();assert.equal(h.tabs.length,3);assert.equal(h.original.cells.get('22,1'),'Existing customer');assert.equal(h.dashboard.cells.get('6,1'),"=SUM('Greekee Orders — TEST'!V2:V)");assert.equal(h.dashboard.charts.length,4);assert.equal(h.post(order()).ok,true);assert.equal(h.original.cells.get('22,1'),'Existing customer');assert.equal(h.orders.cells.get('2,4'),"'=IMPORTXML(\"bad\")");assert.equal(h.orders.cells.get('2,17'),26.79);assert.equal(h.orders.cells.get('3,17'),'');assert.equal(h.orders.cells.get('2,22'),1);assert.equal(h.orders.cells.get('3,22'),0);});
test('retry and older revisions update rows without duplicating orders',()=>{const h=harness(),o=order();h.post(o);h.post(o);assert.equal(h.orders.getLastRow(),3);o.revision=2;o.payment_status='paid';o.order_status='completed';h.post(o);assert.equal(h.orders.cells.get('2,11'),'Delivered');assert.equal(h.orders.cells.get('2,23'),26.79);assert.equal(h.orders.cells.get('2,24'),0);h.post({...o,revision:1,order_status:'pending'});assert.equal(h.orders.cells.get('2,11'),'Delivered');assert.equal(h.orders.getLastRow(),3);});
test('partial write reserves a stable key for repair',()=>{const h=harness(),o=order();h.orders.failNextData();assert.equal(h.post(o).ok,false);assert.equal(h.orders.cells.get('2,1'),'test-order:a');assert.equal(h.post(o).ok,true);assert.equal(h.orders.getLastRow(),3);assert.equal(h.orders.cells.get('2,20'),1);});
test('wrong environment, unsigned and expired requests do not write',()=>{const h=harness(),o=order();assert.equal(h.post(o,{environment:'LIVE'}).ok,false);assert.equal(h.post(o,{badSignature:true}).ok,false);assert.equal(h.post(o,{timestamp:1}).ok,false);assert.equal(h.orders.getLastRow(),1);});
