const {test}=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');const crypto=require('node:crypto');
const secret='test-only-shared-secret-01234567890123456789';
const headers=['Name','Product','Quantity','Status','Order date','Delivery date','Price','Sales platform','Point of contact','Notes'];
function fakeSheet(name){const cells=new Map();let maxRows=100,maxCols=22,failData=false;const key=(r,c)=>r+','+c;
 const sheet={name,cells,getName:()=>name,getMaxRows:()=>maxRows,getMaxColumns:()=>maxCols,insertRowsAfter(_,n){maxRows+=n;},insertColumnsAfter(_,n){maxCols+=n;},getLastRow(){return Math.max(21,...[...cells.keys()].map(k=>Number(k.split(',')[0])));},getRange(r,c,n=1,m=1){if(typeof r==='string'){assert.equal(r,'K1:V20');[r,c,n,m]=[1,11,20,12];}return {getValues:()=>Array.from({length:n},(_,i)=>Array.from({length:m},(_,j)=>cells.get(key(r+i,c+j))??'')),getDisplayValues(){return this.getValues().map(row=>row.map(String));},getFormulas(){return this.getValues().map(row=>row.map(v=>typeof v==='string'&&v.startsWith('=')?v:''));},getCell(i,j){return sheet.getRange(r+i-1,c+j-1);},setFormula(f){cells.set(key(r,c),f);},setValues(values){if(failData&&c===1&&r>=22){failData=false;throw Error('Simulated connection failure');}values.forEach((row,i)=>row.forEach((v,j)=>cells.set(key(r+i,c+j),v)));},setDataValidation(){return this;},clearDataValidations(){return this;},setNumberFormat(){return this;}};},failNextData(){failData=true;}};
 sheet.getRange(21,1,1,10).setValues([headers]);sheet.getRange(22,1,1,10).setValues([['Existing customer','Berry Bliss',2,'Delivered','2026-07-01','2026-07-01',17.8,'Whatsapp','Fiona','manual history']]);sheet.getRange(2,11).setFormula('=SUMIF(D22:D326,"Delivered",C22:C326)');return sheet;}
function harness(){const sheet=fakeSheet("🌟FIO's ORDERS Q3'26");let locked=false;const ctx=vm.createContext({console:{error(){}},PropertiesService:{getScriptProperties:()=>({getProperty:()=>secret})},SpreadsheetApp:{openById:()=>({getSheets:()=>[sheet]}),flush(){},newDataValidation:()=>({requireValueInList(){return this;},setAllowInvalid(){return this;},build(){return {};}})},LockService:{getScriptLock:()=>({waitLock(){locked=true;},hasLock:()=>locked,releaseLock(){locked=false;}})},Utilities:{Charset:{UTF_8:'utf8'},computeHmacSha256Signature:(payload,key)=>[...crypto.createHmac('sha256',key).update(payload).digest()],formatDate:()=>''},ContentService:{MimeType:{JSON:'json'},createTextOutput:s=>({setMimeType:()=>s})}});vm.runInContext(fs.readFileSync('google-sheets/Code.gs','utf8'),ctx);return {sheet,post(o,{badSignature=false,timestamp=Date.now()}={}){const payload=JSON.stringify({timestamp,order:o});const signature=badSignature?'invalid':crypto.createHmac('sha256',secret).update(payload).digest('hex');return JSON.parse(ctx.doPost({postData:{contents:JSON.stringify({payload,signature})}}));}};}
function order(){return {id:'test-order',order_number:'GK-TEST',location:'Punggol',order_date:'2026-09-24',fulfillment_date:'2026-09-25',customer_name:'=IMPORTXML("bad")',revision:1,order_status:'pending',payment_status:'unpaid',source:'Website',notes:'Extra cold',point_of_contact:'Fiona',subtotal_cents:2380,discount_cents:101,total_cents:2679,delivery_fee_cents:400,items:[{id:'a',name:'Berry Bliss',sheet_name:'Berry Bliss',quantity:2,addons:[{name:'Mango',quantity:1,unit_cents:100}],line_cents:1980},{id:'b',name:'Plain',sheet_name:'Plain',quantity:1,addons:[],line_cents:400}]};}
test('signed sync appends by location and preserves existing history and formulas',()=>{const h=harness(),o=order();assert.equal(h.post(o).ok,true);assert.equal(h.sheet.cells.get('22,1'),'Existing customer');assert.equal(h.sheet.cells.get('23,1'),"'=IMPORTXML(\"bad\")");assert.equal(h.sheet.cells.get('23,4'),'Pending confirmation');assert.equal(h.sheet.cells.get('23,3'),2);assert.equal(h.sheet.cells.get('2,11'),'=SUMIF(D22:D,"Delivered",C22:C)');assert.equal(h.sheet.cells.get('23,7')+h.sheet.cells.get('24,7'),22.79);assert.equal(h.sheet.cells.get('23,28'),26.79);assert.equal(h.sheet.cells.get('24,28'),'');});
test('retries and older revisions do not append duplicates or undo updates',()=>{const h=harness(),o=order();h.post(o);h.post(o);assert.equal(h.sheet.getLastRow(),24);o.revision=2;o.payment_status='paid';o.order_status='completed';h.post(o);assert.equal(h.sheet.cells.get('23,4'),'Delivered');h.post({...o,revision:1,order_status:'pending'});assert.equal(h.sheet.cells.get('23,4'),'Delivered');assert.equal(h.sheet.getLastRow(),24);});
test('partial failure reserves a stable row so retry repairs instead of duplicates',()=>{const h=harness(),o=order();h.sheet.failNextData();assert.equal(h.post(o).ok,false);assert.equal(h.sheet.cells.get('23,23'),'test-order:a');assert.equal(h.post(o).ok,true);assert.equal(h.sheet.getLastRow(),24);assert.equal(h.sheet.cells.get('23,25'),1);});
test('unsigned, expired, and wrong-quarter requests do not touch existing data',()=>{const h=harness(),o=order();assert.equal(h.post(o,{badSignature:true}).ok,false);assert.equal(h.post(o,{timestamp:1}).ok,false);assert.equal(h.post({...o,order_date:'2026-10-01'}).ok,false);assert.equal(h.sheet.getLastRow(),22);});
test('occupied metadata columns fail closed instead of overwriting content',()=>{const h=harness();h.sheet.cells.set('24,24','Existing unrelated value');assert.equal(h.post(order()).ok,false);assert.equal(h.sheet.cells.get('24,24'),'Existing unrelated value');});
