'use strict';
const {createHmac}=require('node:crypto');
const {AppError,assert}=require('./orders');
function config(){const url=process.env.SUPABASE_URL,key=process.env.SUPABASE_SECRET_KEY,publishable=process.env.SUPABASE_PUBLISHABLE_KEY;assert(url&&key&&publishable,'Ordering is not connected yet. Please contact us on WhatsApp.',503);assert(/^https:\/\/[a-z0-9-]+\.supabase\.co$/.test(url),'Supabase URL is not configured correctly.',503);return {url,key,publishable};}
async function supa(path,{method='GET',body,headers={},auth=false}={}){
 const {url,key,publishable}=config();
 const response=await fetch(url+path,{method,headers:{apikey:auth?publishable:key,...(!auth&&key.startsWith('eyJ')?{Authorization:'Bearer '+key}:{}),'Content-Type':'application/json',...headers},...(body!==undefined?{body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(10000)});
 const data=await response.json().catch(()=>null);
 if(!response.ok){const error=new AppError(response.status>=500?503:response.status,auth?'Sign-in failed. Check your details and try again.':'Could not save this change. Please try again.');error.code=data?.code;error.detail=data?.message||'';throw error;}return data;
}
function cookie(req,name){const found=(req.headers.cookie||'').split(';').map(s=>s.trim()).find(s=>s.startsWith(name+'='));return found?decodeURIComponent(found.slice(name.length+1)):'';}
function sessions(res,session){const secure=process.env.NODE_ENV==='production'||process.env.VERCEL?' Secure;':'';const attr=`; Path=/; HttpOnly; SameSite=Strict;${secure}`;res.setHeader('Set-Cookie',[`gk_access=${encodeURIComponent(session?.access_token||'')}; Max-Age=${session?session.expires_in||3600:0}${attr}`,`gk_refresh=${encodeURIComponent(session?.refresh_token||'')}; Max-Age=${session?604800:0}${attr}`]);}
async function staffFromToken(token){assert(token,'Please sign in.',401);let user;try{user=await supa('/auth/v1/user',{auth:true,headers:{Authorization:'Bearer '+token}});}catch(e){if(e.status>=500)throw e;throw new AppError(401,'Please sign in again.');}const rows=await supa('/rest/v1/greekee_staff?user_id=eq.'+encodeURIComponent(user.id)+'&active=eq.true&select=*');assert(rows?.length===1,'Your account does not have partner access.',403);return {...rows[0],email:user.email};}
const requireStaff=req=>staffFromToken(cookie(req,'gk_access'));
function origin(req){const value=req.headers.origin;assert(value&&value!=='null','Please open the form on the Greekee website.',403);let host;try{host=new URL(value).host;}catch{throw new AppError(403,'Invalid origin.');}assert(host===req.headers.host,'Please open the form on the Greekee website.',403);}
function body(req){assert((req.headers['content-type']||'').startsWith('application/json'),'Expected JSON.',415);let b=req.body;if(typeof b==='string'){assert(Buffer.byteLength(b)<30000,'Order is too large.',413);try{b=JSON.parse(b);}catch{throw new AppError(400,'Invalid request.');}}assert(b&&typeof b==='object'&&!Array.isArray(b),'Invalid request.');assert(Buffer.byteLength(JSON.stringify(b))<30000,'Order is too large.',413);return b;}
function send(res,status,data){res.setHeader('Cache-Control','no-store');res.setHeader('Content-Type','application/json');res.statusCode=status;res.end(JSON.stringify(data));}
function handler(fn){return async(req,res)=>{try{await fn(req,res);}catch(e){if(e.status>=500||!e.status)console.error('Greekee request failed:',e.code||e.name);send(res,e.status||503,{error:e.status?e.message:'Service temporarily unavailable. Please try again.'});}};}
async function limit(req,bucket,max,seconds){const ip=String(req.headers['x-vercel-forwarded-for']||req.socket?.remoteAddress||'unknown').split(',')[0].trim();const key=bucket+':'+createHmac('sha256',config().key).update(ip).digest('hex');const ok=await supa('/rest/v1/rpc/greekee_rate_limit',{method:'POST',body:{p_key:key,p_max:max,p_seconds:seconds}});assert(ok,'Too many attempts. Please wait a few minutes.',429);}
module.exports={config,supa,cookie,sessions,staffFromToken,requireStaff,origin,body,send,handler,limit};
