'use strict';
const $=s=>document.querySelector(s),catalog=GREEKEE_CATALOG;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=c=>'$'+(c/100).toFixed(2);
const labels={pending:'Pending payment',accepted:'Orders accepted',delivered:'Delivered',exception:'Needs Bobby'};
function stage(o){if(o.order_status==='cancelled'||o.payment_status==='refunded')return 'exception';if(o.order_status==='completed')return 'delivered';return o.payment_status==='paid'?'accepted':'pending';}
const badge=s=>`<span class="badge ${esc(s)}">${esc(labels[s])}</span>`;
let staff=null,orders=[],locationFilter='',hasMore=false,detail=null,manualAttempt=null,settings={};
let refreshPromise=null;
function message(s,error=false){$('#message').textContent=s;$('#message').className=error?'error':'';}
async function api(path,options={},retry=true){
 const r=await fetch(path,{...options,headers:{'Content-Type':'application/json',...options.headers}});const data=await r.json();
 if(r.status===401&&retry&&path!=='/api/session'){
  refreshPromise ||= api('/api/session',{method:'POST',body:JSON.stringify({action:'refresh'})},false).finally(()=>{refreshPromise=null;});
  try{await refreshPromise;}catch(e){showLogin();throw e;}
  return api(path,options,false);
 }
 if(!r.ok)throw Error(data.error||'Something went wrong. Please try again.');return data;
}
function showLogin(){staff=null;orders=[];$('#workspace').hidden=true;$('#loginPanel').hidden=false;$('#logout').hidden=true;$('#identity').textContent='';for(const d of document.querySelectorAll('dialog[open]'))d.close();}
async function start(s){staff=s;$('#loginPanel').hidden=true;$('#workspace').hidden=false;$('#logout').hidden=false;$('#identity').textContent=s.display_name;$('#today').textContent=new Date().toLocaleDateString('en-SG',{timeZone:'Asia/Singapore',weekday:'long',day:'numeric',month:'long'});$('#manualForm').elements.location.innerHTML=s.locations.map(l=>`<option>${esc(l)}</option>`).join('');await load();}
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;try{const form=new FormData(e.target);const d=await api('/api/session',{method:'POST',body:JSON.stringify({action:'login',email:form.get('email'),password:form.get('password')})});e.target.reset();message('');await start(d.staff);}catch(e){message(e.message,true);}finally{button.disabled=false;}});
$('#logout').onclick=async()=>{try{await api('/api/session',{method:'POST',body:JSON.stringify({action:'logout'})});showLogin();message('Signed out.');}catch(e){message('Could not sign out. Please retry before leaving this device.',true);}};
async function load(append=false){
 const params=new URLSearchParams({offset:String(append?orders.length:0)});if(locationFilter)params.set('location',locationFilter);for(const name of ['from','to'])if($('#'+name).value)params.set(name,$('#'+name).value);
 if($('#from').value&&$('#to').value&&$('#from').value>$('#to').value)throw Error('The end date must be after the start date.');
 const d=await api('/api/orders?'+params);orders=append?orders.concat(d.orders):d.orders;hasMore=d.has_more;render();
}
function safeLoad(append=false){load(append).catch(e=>message(e.message,true));}
for(const b of document.querySelectorAll('[data-location]'))b.onclick=()=>{locationFilter=b.dataset.location;for(const other of document.querySelectorAll('[data-location]'))other.setAttribute('aria-pressed',String(other===b));safeLoad();};
for(const id of ['search','status'])$('#'+id).addEventListener('input',render);
for(const id of ['from','to'])$('#'+id).onchange=()=>safeLoad();
$('#refresh').onclick=()=>safeLoad();$('#more').onclick=()=>safeLoad(true);
function filtered(){const q=$('#search').value.toLowerCase().trim();return orders.filter(o=>(!q||[o.customer_name,o.order_number,o.phone].some(s=>s.toLowerCase().includes(q)))&&(!$('#status').value||stage(o)===$('#status').value));}
function render(){
 const rows=filtered();const active=rows.filter(o=>stage(o)==='accepted');
 const stats=[['Pending payment',rows.filter(o=>stage(o)==='pending').length,'Waiting for payment check'],['Accepted orders',active.length,'To prepare or hand over'],['Bowls to prepare',active.reduce((n,o)=>n+o.items.reduce((s,i)=>s+i.quantity,0),0),'Accepted orders only'],['Delivered',rows.filter(o=>stage(o)==='delivered').length,'Handed to customers']];
 $('#stats').innerHTML=stats.map(([title,value,hint])=>`<div class="stat"><span>${title}</span><strong>${value}</strong><small>${hint}</small></div>`).join('');
 const dirty=orders.filter(o=>o.revision>o.synced_revision).length;
 $('#listNote').textContent=`${rows.length} matching orders shown${hasMore?' · More available below':''}. Totals above cover the visible orders only. ${settings.sheets_configured?`${dirty} loaded orders awaiting Sheets sync.`:'Sheets sync is not connected yet.'}`;
 $('#more').hidden=!hasMore;
 $('#orderList').innerHTML=rows.length?`<div class="table-scroll"><table><thead><tr><th>Order / customer</th><th>Bowls</th><th>Due / location</th><th>Stage</th><th>Total</th></tr></thead><tbody>${rows.map(o=>`<tr><td><button class="order-link" data-order="${esc(o.id)}">${esc(o.customer_name)}</button><small>${esc(o.order_number)}</small><small>${esc(o.source)}</small></td><td data-label="Items">${o.items.reduce((n,i)=>n+i.quantity,0)}<small>${esc(o.items.map(i=>i.name).join(', '))}</small></td><td data-label="Due">${esc(o.fulfillment_date)}<small>${esc(o.location)} · ${esc(o.fulfillment)}${o.pickup_slot?' · '+esc(new Date(o.pickup_slot).toLocaleTimeString('en-SG',{timeZone:'Asia/Singapore',hour:'numeric',minute:'2-digit'})):''}</small></td><td data-label="Stage">${badge(stage(o))}</td><td>${money(o.total_cents)}</td></tr>`).join('')}</tbody></table></div>`:`<div class="empty"><h3>No bowls on this list yet.</h3><p>Try another filter, or add an order from your messages.</p></div>`;
 for(const b of document.querySelectorAll('[data-order]'))b.onclick=()=>openOrder(b.dataset.order).catch(e=>message(e.message,true));
}
const selectOptions=(values,current)=>values.map(v=>`<option value="${v}" ${current===v?'selected':''}>${labels[v]||v}</option>`).join('');
async function openOrder(id){
 const d=await api('/api/orders?id='+encodeURIComponent(id));detail=d.order;const o=detail;$('#detailNumber').textContent=o.order_number;
 $('#detailContent').innerHTML=`<h2>${esc(o.customer_name)}</h2><p>${esc(o.location)} · ${esc(o.source)} · Ordered ${esc(o.order_date)}</p><div class="meta-grid"><div><b>Phone</b>${esc(o.phone)}</div><div><b>Method</b>${esc(o.fulfillment)}</div>${o.address?`<div><b>Address</b>${esc(o.address)}</div>`:''}<div><b>Point of contact</b>${esc(o.point_of_contact||'—')}</div></div>${o.items.map(i=>`<div class="item-detail"><strong><span>${i.quantity} × ${esc(i.name)}</span><span>${money(i.line_cents)}</span></strong><small>${i.addons.length?'Per bowl: '+i.addons.map(a=>esc(a.name)+' × '+a.quantity+' ('+money(a.unit_cents)+' each)').join(', '):'No extra add-ons'}</small></div>`).join('')}<p class="small">Subtotal ${money(o.subtotal_cents)} · Discount ${money(o.discount_cents)} · Delivery ${money(o.delivery_fee_cents)}${o.adjustment_reason?' · '+esc(o.adjustment_reason):''}</p><div class="total-line"><span>Order total</span><strong>${money(o.total_cents)}</strong></div>
 <form id="updateForm"><div class="form-grid"><label>Order stage<select name="stage" ${stage(o)==='exception'?'disabled':''}>${selectOptions(['pending','accepted','delivered'],stage(o))}</select></label>${stage(o)==='exception'?'<p class="small">This older order is cancelled or refunded. Ask Bobby before changing it.</p>':''}<label>Customer name<input name="customer_name" value="${esc(o.customer_name)}" maxlength="100" required></label><label>Phone country<select name="phone_country" aria-label="Phone country code"></select></label><label>Phone number<input name="phone" type="tel" maxlength="30" required></label><label>Collection / delivery date<input name="fulfillment_date" type="date" value="${esc(o.fulfillment_date)}" required></label>${o.fulfillment==='pickup'?`<label>Pickup time (Singapore)<input name="pickup_time" type="time" value="${o.pickup_slot?new Date(o.pickup_slot).toLocaleTimeString('en-GB',{timeZone:'Asia/Singapore',hour:'2-digit',minute:'2-digit'}):''}"></label>`:''}${o.fulfillment==='delivery'?`<label class="wide">Delivery address<textarea name="address" maxlength="400" required>${esc(o.address)}</textarea></label>`:''}<label class="wide">Notes<textarea name="notes" maxlength="1500">${esc(o.notes)}</textarea></label></div><label class="verify" id="paymentVerify" hidden><input name="payment_verified" type="checkbox">I checked the payment in our bank account, or confirmed the balance is $0 after discount.</label><p class="small">${o.payment_checked_at?'Payment last checked '+esc(new Date(o.payment_checked_at).toLocaleString('en-SG',{timeZone:'Asia/Singapore'}))+'. See history below.':'Payment has not been checked yet.'}</p><p class="error" id="detailError" role="alert"></p><button type="submit" class="primary">Save changes</button></form>
 <h3>Sheets sync</h3><p class="small">${o.synced_revision>=o.revision?'Up to date.':esc(o.last_sync_error||'Waiting to sync. Use Retry Sheets sync on the order list.')}</p><h3>Change history</h3><ul class="history">${d.events.length?d.events.map(e=>`<li><strong>${esc(e.actor_name)}</strong><small>${esc(new Date(e.changed_at).toLocaleString('en-SG',{timeZone:'Asia/Singapore'}))}</small>${Object.entries(e.changes).map(([key,change])=>`${esc(key.replaceAll('_',' '))}: ${esc(change.before??'—')} → ${esc(change.after??'—')}`).join('<br>')}</li>`).join(''):'<li>No changes yet.</li>'}</ul>`;
 const form=$('#updateForm');
 if(!staff.locations.includes(o.location)){
  form.replaceWith(Object.assign(document.createElement('p'),{className:'small',textContent:`This order is assigned to ${o.location==='Hougang'?'Caleb':'Fiona'}. You can see its details here; ask them to make changes.`}));
  $('#detailDialog').showModal();return;
 }
 GREEKEE_PHONE.bind(form.elements.phone_country,form.elements.phone,o.phone);form.elements.stage.onchange=()=>{$('#paymentVerify').hidden=(form.elements.stage.value==='pending'?'unpaid':'paid')===o.payment_status;form.elements.payment_verified.checked=false;};
 form.onsubmit=async e=>{e.preventDefault();e.submitter.disabled=true;$('#detailError').textContent='';try{
  const b={id:o.id,revision:o.revision};for(const k of ['customer_name','fulfillment_date','notes','address'])if(form.elements[k]&&form.elements[k].value!==String(o[k]??''))b[k]=form.elements[k].value;
  if(stage(o)!=='exception'){const target=form.elements.stage.value;const nextOrder={pending:'pending',accepted:'confirmed',delivered:'completed'}[target],nextPayment=target==='pending'?'unpaid':'paid';if(nextOrder!==o.order_status)b.order_status=nextOrder;if(nextPayment!==o.payment_status){b.payment_status=nextPayment;b.payment_verified=form.elements.payment_verified.checked;}}
  const phone=GREEKEE_PHONE.normalize(form.elements.phone_country,form.elements.phone);if(phone!==o.phone)b.phone=phone;
  if(form.elements.pickup_time){const time=form.elements.pickup_time.value;const value=time?new Date(form.elements.fulfillment_date.value+'T'+time+':00+08:00').toISOString():null;if(value!==(o.pickup_slot?new Date(o.pickup_slot).toISOString():null))b.pickup_slot=value;}
  if(Object.keys(b).length===2){$('#detailDialog').close();return;}
  const saved=await api('/api/orders',{method:'PATCH',body:JSON.stringify(b)});$('#detailDialog').close();await load();message(saved.sync.state==='pending'?'Order saved. Sheets sync is pending; you can retry it.':'Order updated.');
 }catch(e){$('#detailError').textContent=e.message;}finally{e.submitter.disabled=false;}};
 if(!$('#detailDialog').open)$('#detailDialog').showModal();
}
for(const b of document.querySelectorAll('[data-close]'))b.onclick=()=>$('#'+b.dataset.close).close();
$('#sync').onclick=async e=>{e.target.disabled=true;try{let count=0,fail=0,more=false;for(let i=0;i<10;i++){const r=await api('/api/sync',{method:'POST',body:'{}'});count+=r.processed;fail+=r.failed;more=r.more;if(!r.more||r.failed)break;}await load();message(fail?'Some orders are still waiting to sync. Check the Sheets setup, then retry.':`Synced ${count} orders.${more?' More remain; tap retry again.':''}`,Boolean(fail));}catch(e){message(e.message,true);}finally{e.target.disabled=false;}};
// Manual order builder
const form=$('#manualForm');$('#manualArea').innerHTML=catalog.east.map(e=>`<option>${esc(e[0])}</option>`).join('');
function manualRoute(){if(form.elements.fulfillment.value!=='delivery')return form.elements.location.value;const area=catalog.east.find(e=>e[0]===form.elements.delivery_area.value);return form.elements.delivery_region.value==='East'?(area?.[2]||'Punggol'):'Punggol';}
function syncManualRoute(){const delivery=form.elements.fulfillment.value==='delivery';$('#manualDelivery').hidden=!delivery;form.elements.location.disabled=delivery;if(delivery)form.elements.location.value=manualRoute();else if(!form.elements.location.value)form.elements.location.value=staff.locations[0];}
$('#manualMethod').onchange=()=>{syncManualRoute();updateTotal();};
GREEKEE_PHONE.bind(form.elements.phone_country,form.elements.phone);
$('#newOrder').onclick=()=>{form.reset();manualAttempt=null;$('#manualError').textContent='';$('#manualItems').replaceChildren();const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Singapore'}).format(new Date());form.elements.phone_country.value='SG';form.elements.order_date.value=today;form.elements.fulfillment_date.value=today;form.elements.location.value=locationFilter||staff.locations[0];form.elements.point_of_contact.value=staff.display_name;syncManualRoute();addItem();$('#addDialog').showModal();};
$('#addItem').onclick=()=>addItem();
function addItem(){
 const row=document.createElement('div');row.className='manual-item';row.innerHTML=`<div class="item-top"><label>Bowl / item<select class="product">${catalog.products.map(p=>`<option value="${p.id}">${esc(p.kind==='custom'?'Build Your Own — '+p.name:p.name)} · ${money(p.cents)}</option>`).join('')}<option value="special-order">Special order / agreed price</option></select></label><label>Quantity<input class="quantity" type="number" min="1" max="100" value="1" required></label><button type="button" class="quiet remove-item">Remove</button></div><div class="custom-product form-grid" hidden><label>Item name<input class="custom-name" maxlength="100"></label><label>Agreed base price each ($)<input class="custom-price" type="number" min="0" step="0.01" value="0"></label></div><div class="addons"></div><button type="button" class="quiet add-addon">+ Add topping / extra</button>`;
 $('#manualItems').append(row);row.querySelector('.product').onchange=()=>{row.querySelector('.custom-product').hidden=row.querySelector('.product').value!=='special-order';const yogurt=row.querySelector('.product').value.startsWith('jy-');row.querySelector('.add-addon').disabled=yogurt;if(yogurt)row.querySelector('.addons').replaceChildren();updateTotal();};row.querySelector('.remove-item').onclick=()=>{row.remove();updateTotal();};row.querySelector('.add-addon').onclick=()=>addAddon(row);row.oninput=updateTotal;updateTotal();
}
function addAddon(row){const div=document.createElement('div');div.className='addon-row';div.innerHTML=`<label>Add-on<select class="addon-name">${catalog.toppings.map(t=>`<option>${esc(t)}</option>`).join('')}<option value="__other">Other extra…</option></select></label><label>Per bowl<input class="addon-qty" type="number" min="1" max="20" value="1" required></label><label>Each ($)<input class="addon-price" type="number" min="0" max="100" step="0.01" value="1.00" required></label><button type="button" class="quiet remove-addon" aria-label="Remove add-on">×</button><label class="custom-addon" hidden>Extra name<input class="addon-custom" maxlength="80" placeholder="e.g. extra yogurt 50g"></label>`;row.querySelector('.addons').append(div);div.querySelector('.addon-name').onchange=()=>{div.querySelector('.custom-addon').hidden=div.querySelector('.addon-name').value!=='__other';};div.querySelector('.remove-addon').onclick=()=>{div.remove();updateTotal();};updateTotal();}
function manualItems(){return [...document.querySelectorAll('.manual-item')].map(row=>({product_id:row.querySelector('.product').value,custom_name:row.querySelector('.custom-name').value,custom_unit_cents:Math.round(Number(row.querySelector('.custom-price').value)*100),quantity:Number(row.querySelector('.quantity').value),addons:[...row.querySelectorAll('.addon-row')].map(a=>({name:a.querySelector('.addon-name').value==='__other'?a.querySelector('.addon-custom').value:a.querySelector('.addon-name').value,quantity:Number(a.querySelector('.addon-qty').value),unit_cents:Math.round(Number(a.querySelector('.addon-price').value)*100)}))}));}
function updateTotal(){const subtotal=manualItems().reduce((n,i)=>n+((catalog.products.find(p=>p.id===i.product_id)?.cents??i.custom_unit_cents)+i.addons.reduce((s,a)=>s+a.quantity*a.unit_cents,0))*i.quantity,0);let fee=0;if(form.elements.fulfillment.value==='delivery'){fee=form.elements.delivery_fee.value!==''?Math.round(Number(form.elements.delivery_fee.value)*100):form.elements.delivery_region.value==='East'?(subtotal>=catalog.eastFreeCents?0:catalog.east.find(e=>e[0]===form.elements.delivery_area.value)[1]):subtotal>=catalog.otherFreeCents?0:catalog.otherDeliveryCents;}$('#manualTotal').textContent=money(subtotal+fee-Math.round(Number(form.elements.discount.value)*100));}
form.addEventListener('input',()=>{syncManualRoute();updateTotal();});form.addEventListener('change',()=>{syncManualRoute();updateTotal();});
form.onsubmit=async e=>{e.preventDefault();e.submitter.disabled=true;$('#manualError').textContent='';try{const route=manualRoute();if(!staff.locations.includes(route))throw Error('This delivery belongs to '+(route==='Hougang'?'Caleb':'Fiona')+'. Ask them to add it.');const b=Object.fromEntries(new FormData(form));b.location=route;b.phone=GREEKEE_PHONE.normalize(form.elements.phone_country,form.elements.phone);delete b.phone_country;delete b.delivery_fee;delete b.discount;b.manual=true;b.items=manualItems();b.discount_cents=Math.round(Number(form.elements.discount.value)*100);if(form.elements.delivery_fee.value!=='')b.delivery_fee_cents=Math.round(Number(form.elements.delivery_fee.value)*100);b.pickup_slot='';const fingerprint=JSON.stringify(b);if(!manualAttempt||manualAttempt.fingerprint!==fingerprint)manualAttempt={fingerprint,key:crypto.randomUUID()};b.request_key=manualAttempt.key;const saved=await api('/api/orders',{method:'POST',body:JSON.stringify(b)});$('#addDialog').close();await load();message(saved.order_number+' saved as pending payment. Open it once payment is checked.');}catch(e){$('#manualError').textContent=e.message;}finally{e.submitter.disabled=false;}};
(async()=>{try{settings=await api('/api/config');}catch{}try{let result;try{result=await api('/api/session',{},false);}catch{result=await api('/api/session',{method:'POST',body:JSON.stringify({action:'refresh'})},false);}await start(result.staff);}catch{showLogin();}})();
